const ACTION_TYPES = {
    API_PENDING: 'API_PENDING',
    API_SUCCESS: 'API_SUCCESS',
    API_ERROR: 'API_ERROR',
    API_MULTIPLE_SUCCESS: 'API_MULTIPLE_SUCCESS',
    API_AUTH : 'API_AUTH',
  };
  export default ACTION_TYPES;